const MOCK_EVIDENCE = [
  {
    _id: "e1",
    title: "Crime Scene Photo A",
    caseNumber: "CASE-2024-001",
    category: "image",
    status: "active",
    collectedBy: "Det. Sarah Kim",
    collectionDate: "2024-11-10",
    location: "123 Oak St, Room 4",
    fileSize: 3204000,
    mimeType: "image/jpeg",
    originalName: "scene_a.jpg",
    description:
      "Exterior photograph taken at 08:45 hrs showing forced entry point.",
    tags: ["exterior", "entry-point"],
    chainOfCustody: [
      {
        action: "Evidence Collected",
        officer: "Det. Sarah Kim",
        timestamp: "2024-11-10T09:00:00Z",
        notes: "Photographed at scene",
      },
      {
        action: "Logged to Vault",
        officer: "Sgt. M. Torres",
        timestamp: "2024-11-10T14:00:00Z",
        notes: "",
      },
    ],
    createdAt: "2024-11-10T14:00:00Z",
    updatedAt: "2024-11-10T14:00:00Z",
  },
  {
    _id: "e2",
    title: "Witness Statement — J. Doe",
    caseNumber: "CASE-2024-001",
    category: "document",
    status: "pending",
    collectedBy: "Off. R. Patel",
    collectionDate: "2024-11-11",
    location: "Precinct 7 Interview Room B",
    fileSize: 189000,
    mimeType: "application/pdf",
    originalName: "witness_doe.pdf",
    description:
      "Signed statement from primary witness detailing events of Nov 9th.",
    tags: ["witness", "statement"],
    chainOfCustody: [
      {
        action: "Document Created",
        officer: "Off. R. Patel",
        timestamp: "2024-11-11T11:00:00Z",
        notes: "",
      },
    ],
    createdAt: "2024-11-11T11:00:00Z",
    updatedAt: "2024-11-11T11:00:00Z",
  },
  {
    _id: "e3",
    title: "Surveillance Audio Recording",
    caseNumber: "CASE-2024-002",
    category: "audio",
    status: "active",
    collectedBy: "Det. Sarah Kim",
    collectionDate: "2024-11-12",
    location: "Midtown Security Office",
    fileSize: 45600000,
    mimeType: "audio/mp3",
    originalName: "surveillance_11-12.mp3",
    description:
      "24-hour audio capture from exterior mic, approx. 3 hours flagged.",
    tags: ["surveillance", "audio", "key-evidence"],
    chainOfCustody: [
      {
        action: "Audio Extracted",
        officer: "Tech. A. Brooks",
        timestamp: "2024-11-12T16:00:00Z",
        notes: "Full 24hr file extracted",
      },
      {
        action: "Segment Flagged",
        officer: "Det. Sarah Kim",
        timestamp: "2024-11-13T09:30:00Z",
        notes: "Hours 02:00–05:00 flagged as relevant",
      },
    ],
    createdAt: "2024-11-12T16:00:00Z",
    updatedAt: "2024-11-13T09:30:00Z",
  },
  {
    _id: "e4",
    title: "CCTV Footage — Entrance",
    caseNumber: "CASE-2024-002",
    category: "video",
    status: "archived",
    collectedBy: "Tech. A. Brooks",
    collectionDate: "2024-11-13",
    location: "Building Lobby",
    fileSize: 890000000,
    mimeType: "video/mp4",
    originalName: "cctv_entrance_13nov.mp4",
    description: "Lobby CCTV footage from 00:00–06:00, Nov 13th.",
    tags: ["cctv", "lobby"],
    chainOfCustody: [
      {
        action: "Footage Downloaded",
        officer: "Tech. A. Brooks",
        timestamp: "2024-11-13T10:00:00Z",
        notes: "",
      },
    ],
    createdAt: "2024-11-13T10:00:00Z",
    updatedAt: "2024-11-14T08:00:00Z",
  },
  {
    _id: "e5",
    title: "Forensic Lab Report",
    caseNumber: "CASE-2024-001",
    category: "document",
    status: "active",
    collectedBy: "Dr. L. Vasquez",
    collectionDate: "2024-11-15",
    location: "Forensic Lab, Bay 3",
    fileSize: 520000,
    mimeType: "application/pdf",
    originalName: "forensic_lab_001.pdf",
    description: "DNA and fingerprint analysis results from case items 1–8.",
    tags: ["forensics", "DNA", "fingerprint"],
    chainOfCustody: [
      {
        action: "Report Filed",
        officer: "Dr. L. Vasquez",
        timestamp: "2024-11-15T17:00:00Z",
        notes: "Signed and certified",
      },
    ],
    createdAt: "2024-11-15T17:00:00Z",
    updatedAt: "2024-11-15T17:00:00Z",
  },
  {
    _id: "e6",
    title: "Encrypted Device Image",
    caseNumber: "CASE-2024-003",
    category: "other",
    status: "pending",
    collectedBy: "Det. J. Moore",
    collectionDate: "2024-11-16",
    location: "Suspect Residence",
    fileSize: 64000000000,
    mimeType: "application/octet-stream",
    originalName: "device_image.dd",
    description: "Forensic bit-copy of seized laptop hard drive.",
    tags: ["digital", "disk-image"],
    chainOfCustody: [
      {
        action: "Device Seized",
        officer: "Det. J. Moore",
        timestamp: "2024-11-16T14:00:00Z",
        notes: "Warrant #W-2024-44",
      },
      {
        action: "Imaging Completed",
        officer: "Tech. A. Brooks",
        timestamp: "2024-11-17T11:00:00Z",
        notes: "",
      },
    ],
    createdAt: "2024-11-17T11:00:00Z",
    updatedAt: "2024-11-17T11:00:00Z",
  },
];

const MOCK_USER = {
  name: "Det. Sarah Kim",
  email: "s.kim@pd.gov",
  role: "investigator",
  department: "Homicide Division",
  badgeNumber: "B-1142",
};

const STATS = {
  total: MOCK_EVIDENCE.length,
  byCategory: [
    { _id: "image", count: 1 },
    { _id: "document", count: 2 },
    { _id: "audio", count: 1 },
    { _id: "video", count: 1 },
    { _id: "other", count: 1 },
  ],
  byStatus: [
    { _id: "active", count: 3 },
    { _id: "pending", count: 2 },
    { _id: "archived", count: 1 },
  ],
  recentUploads: MOCK_EVIDENCE.slice(0, 4),
};

const NAV = [
  { path: "dashboard", label: "Dashboard", icon: "⬡" },
  { path: "upload", label: "Upload Evidence", icon: "⬆" },
  { path: "evidence", label: "Evidence Vault", icon: "🗂" },
  { path: "reports", label: "Reports", icon: "📊" },
];

export { MOCK_EVIDENCE, MOCK_USER, STATS, NAV };
